/* AI Check — WoodWing Studio plug-in (Content Station SDK custom application).
   One file, hosted on HTTPS, registered in Management Console → Integrations → Studio → Plug-ins → Studio.
   Runs inside Studio's own page on the person's session: no sign-in, no ticket, no cross-origin calls.
   GENERATED by build-plugin.py from studio-plugin/src/*.js + the shared review page (build-review-page.py) + review-app/enrich.js. */
(function () {
  if (typeof ContentStationSdk === 'undefined') { return; }   // not a Studio context
  var VERSION = '__VERSION__';
  var TAG = '[ai-check]';
